// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ReportGenerator {
	
	
	public partial class dialogShowStats : Gtk.Dialog {
		
		public dialogShowStats() {
			this.Build();
		}
		
		protected virtual void OnAcceptClicked(object sender, System.EventArgs e) {
		}
		
		protected virtual void OnCancelClicked(object sender, System.EventArgs e) {
		}
	}
}
