/*
    Zaspe# - Attendance management
    Copyright (C) 2006, 2007 Milton Pividori

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using System;
using Gentle.Framework;

namespace ZaspeSharp.Events
{
	/// <summary>
	/// Description of TipoEventoPropiedades.
	/// </summary>
	public partial class EventType
	{
		public int Id {
			get { return id; }
		}
		
		[TableColumn("name", NotNull=true)]//, PrimaryKey(AutoGenerated=false)]
		public string Name {
			get { return name; }
			set { name = value; }
		}
	}
}
