/*
    Zaspe# - Attendance management
    Copyright (C) 2006, 2007 Milton Pividori

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

using System;

using ZaspeSharp.Persons;
using ZaspeSharp.Events;

using Gentle.Framework;

namespace ZaspeSharp.Attendances
{
	/// <summary>
	/// Description of AsistenciaPropiedades.
	/// </summary>
	public partial class Attendance
	{
		[TableColumn("id_person", NotNull=true), PrimaryKey(AutoGenerated=false)]
		public int PersonID {
			get { return this.aPerson.Id; }
			set {
				PersonsManager pm = PersonsManager.Instance;
				this.aPerson = pm.RetrieveById(value);
			}
		}
		
		[TableColumn("id_event", NotNull=true), PrimaryKey(AutoGenerated=false)]
		public int EventID {
			get {
				return this.anEvent.Id;
			}
			
			set {
				EventsManager em = EventsManager.Instance;
				this.anEvent = em.Retrieve(value);
			}
		}
	}
}
